name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
      include:
        os: centos-7.4
        compiler:
          - gcc-8.4
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: run test
      run: ./build/memory_log_store_test && ./build/nanolog_test
